# syntax=docker/dockerfile:1

FROM golang:1.17-alpine

ENV HOST="127.0.0.1"
ENV PORT="50051"

WORKDIR /app

COPY go.mod ./
COPY go.sum ./

RUN go mod download

COPY . ./

RUN go build -o /client ./cmd/client/main.go

CMD ["sh", "-c", "/client --host ${HOST} --port ${PORT} --random"]
