version: "3.3"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    environment:
      HOST: "server"