version: "3.3"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
  client-1:
    build:
      context: .
      dockerfile: Dockerfile.client
    environment:
      HOST: "server"
    deploy:
      mode: replicated
      replicas: 3